05-koajs/01-chat-app
js-tasks-ru/nodejs-20220114_evgeniy-budaev pull request #7
Opened 2022-02-01 13:23 UTC by EvgeniyBudaev

2022-02-01 13:24 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-02-04 15:21 UTC, tadjik1 commented on 05-koajs/01-chat-app/app.js
> +		resolvers.forEach((resolver) => resolver(message));
надо обязательно очищать этот список после того как ответ отправлен, иначе клиенты "подвиснут" и будут использоваться при каждом запросе.

2022-02-04 15:21 UTC, tadjik1 requested changes
@EvgeniyBudaev отличная работа, идея абсолютно верная. однако немного надо исправить (точнее дополнить реализацию)

2022-02-06 07:09 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2022-02-07 04:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-02-07 05:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-02-07 05:10 UTC, EvgeniyBudaev commented on 05-koajs/01-chat-app/app.js
> +		resolvers.forEach((resolver) => resolver(message));
Исправил

2022-02-07 05:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2022-02-08 16:14 UTC, tadjik1 approved these changes
@EvgeniyBudaev все последующие задачи решены тоже отлично 👍

2022-02-08 16:15 UTC, merged